version: '3'
services:
  db:
    image: mysql:8.0.23

    environment:
      - MYSQL_ROOT_HOST=${DB_ROOT_HOST}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

    ports:
      - '3306:3306'

    volumes:
      - mysqldata:/var/lib/mysql

    networks:
      - backend

  app:
    image: node:16.18-buster

    tty: true

    ports:
      - '8001:8001'

    volumes:
      - .:/app

    working_dir: /app

    command: >
      sh -c "npm install &&
             npm install -g pm2 &&
             pm2-runtime index.js"

    networks:
      - backend

    depends_on:
      db:
        condition: service_healthy

networks:
  backend:

volumes:
  mysqldata:
